version: '3.8'

services:
  web: # 이름을 단순히 web으로 통일하면 관리하기 편해요
    image: umleeho/my-web-app:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=172.31.38.213 # Redis 서버 사설 IP
    command: python app.py
    restart: always

  worker: # 워커도 마찬가지로 내 이미지를 사용
    image: umleeho/my-web-app:latest
    environment:
      - REDIS_HOST=172.31.38.213
    command: python worker.py
    restart: always