upstream my_servers {
    server web-1:5000;
    server web-2:5000;
    server web-3:5000;
}

server {
    listen 80;

    location / {
        proxy_pass http://my_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}